### ISSUE TITLE
compilation error in arch linux 

### ISSUE THREAD

**Issue by Malifick** [antoniograzioli/Autodafe-Drums#3]
src/DrumsMixer.cpp:169:7: warning: ‘virtual void DrumsMixer::fromJson(json_t*)’ can be marked override [-Wsuggest-override]
  void fromJson(json_t *rootJm) {
       ^~~~~~~~
src/DrumsMixer.cpp:206:6: error: virtual function ‘virtual void DrumsMixer::initialize()’
 void initialize() {
      ^~~~~~~~~~
In file included from ../../include/rack.hpp:6:0,
                 from src/Autodafe.hpp:1,
                 from src/DrumsMixer.cpp:1:
../../include/engine.hpp:62:15: error: overriding final function ‘virtual void rack::Module::initialize()’
  virtual void initialize() final {}
               ^~~~~~~~~~
src/DrumsMixer.cpp:206:6: warning: ‘virtual void DrumsMixer::initialize()’ can be marked override [-Wsuggest-override]
 void initialize() {
      ^~~~~~~~~~
make: *** [../../compile.mk:55: build/src/DrumsMixer.cpp.o] Error 1

**Comment by antoniograzioli** [comment]
there are similar issues on Win and Mac as well..I need to push the updated version for the latest release of Rack, I simply dind't have enough time...

**Comment by Malifick** [comment]
ok

**Comment by Malifick** [comment]
still no dice in arch linux: 
 
 make
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/DrumsMixer.cpp.o src/DrumsMixer.cpp
src/DrumsMixer.cpp:132:7: warning: ‘virtual void DrumsMixer::step()’ can be marked override [-Wsuggest-override]
  void step();
       ^~~~
src/DrumsMixer.cpp:139:9: warning: ‘virtual json_t* DrumsMixer::toJson()’ can be marked override [-Wsuggest-override]
 json_t *toJson() {
         ^~~~~~
src/DrumsMixer.cpp:169:7: warning: ‘virtual void DrumsMixer::fromJson(json_t*)’ can be marked override [-Wsuggest-override]
  void fromJson(json_t *rootJm) {
       ^~~~~~~~
src/DrumsMixer.cpp:206:6: error: virtual function ‘virtual void DrumsMixer::initialize()’
 void initialize() {
      ^~~~~~~~~~
In file included from ../../include/rack.hpp:7:0,
                 from src/Autodafe.hpp:1,
                 from src/DrumsMixer.cpp:1:
../../include/engine.hpp:70:15: error: overriding final function ‘virtual void rack::Module::initialize()’
  virtual void initialize() final {}
               ^~~~~~~~~~
src/DrumsMixer.cpp:206:6: warning: ‘virtual void DrumsMixer::initialize()’ can be marked override [-Wsuggest-override]
 void initialize() {
      ^~~~~~~~~~
src/DrumsMixer.cpp: In constructor ‘DrumsMixerWidget::DrumsMixerWidget()’:
src/DrumsMixer.cpp:478:14: error: ‘createValueLight’ was not declared in this scope
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
              ^~~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: error: ‘GreenValueLight’ was not declared in this scope
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: error: template argument 1 is invalid
src/DrumsMixer.cpp:479:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(100+8, 280+5), &module->ch2MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:479:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:480:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(150+8, 280+5), &module->ch3MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:480:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:481:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(200+8, 280+5), &module->ch4MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:481:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:482:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(250+8, 280+5), &module->ch5MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:482:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:483:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(300+8, 280+5), &module->ch6MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:483:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:484:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(350+8, 280+5), &module->ch7MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:484:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:485:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(400+8, 280+5), &module->ch8MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:485:42: note:   expected a type, got ‘GreenValueLight’
make: *** [../../compile.mk:54: build/src/DrumsMixer.cpp.o] Error 1

**Comment by gmohre** [comment]
I am also having this issue on windows 10.

**Comment by asbaklm** [comment]
and seeing this in Mint:


src/DrumsHiHatOpen.cpp:280:42: note: ‘GreenValueLight’ was not declared ‘constexpr’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(26,65), &module->light));
                                          ^
src/DrumsHiHatOpen.cpp:288:43: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
      addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(10,250), &module->lights[6]));
                                           ^
src/DrumsHiHatOpen.cpp:288:43: note:   expected a type, got ‘GreenValueLight’
src/DrumsHiHatOpen.cpp:289:43: error: the value of ‘GreenValueLight’ is not usable in a constant expression
      addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(10,275), &module->lights[7]));
                                           ^
src/DrumsHiHatOpen.cpp:280:42: note: ‘GreenValueLight’ was not declared ‘constexpr’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(26,65), &module->light));
                                          ^
src/DrumsHiHatOpen.cpp:289:43: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
      addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(10,275), &module->lights[7]));
                                           ^
src/DrumsHiHatOpen.cpp:289:43: note:   expected a type, got ‘GreenValueLight’
../../compile.mk:53: recipe for target 'build/src/DrumsHiHatOpen.cpp.o' failed
make: *** [build/src/DrumsHiHatOpen.cpp.o] Error 1

**Comment by sbcook0** [comment]
sources need updating to compile in v0.5.0

**Comment by AmateurExpert** [comment]
This is what I get (Xubuntu Zesty):

g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/DrumsMixer.cpp.o src/DrumsMixer.cpp
src/DrumsMixer.cpp:132:7: warning: ‘virtual void DrumsMixer::step()’ can be marked override [-Wsuggest-override]
  void step();
       ^~~~
src/DrumsMixer.cpp:139:9: warning: ‘virtual json_t* DrumsMixer::toJson()’ can be marked override [-Wsuggest-override]
 json_t *toJson() {
         ^~~~~~
src/DrumsMixer.cpp:169:7: warning: ‘virtual void DrumsMixer::fromJson(json_t*)’ can be marked override [-Wsuggest-override]
  void fromJson(json_t *rootJm) {
       ^~~~~~~~
src/DrumsMixer.cpp:206:6: error: virtual function ‘virtual void DrumsMixer::initialize()’
 void initialize() {
      ^~~~~~~~~~
In file included from ../../include/rack.hpp:7:0,
                 from src/Autodafe.hpp:1,
                 from src/DrumsMixer.cpp:1:
../../include/engine.hpp:72:15: error: overriding final function ‘virtual void rack::Module::initialize()’
  virtual void initialize() final {}
               ^~~~~~~~~~
src/DrumsMixer.cpp:206:6: warning: ‘virtual void DrumsMixer::initialize()’ can be marked override [-Wsuggest-override]
 void initialize() {
      ^~~~~~~~~~
src/DrumsMixer.cpp: In constructor ‘DrumsMixer::DrumsMixer()’:
src/DrumsMixer.cpp:223:24: warning: ‘rack::Module::Module()’ is deprecated [-Wdeprecated-declarations]
 DrumsMixer::DrumsMixer() {
                        ^
In file included from ../../include/rack.hpp:7:0,
                 from src/Autodafe.hpp:1,
                 from src/DrumsMixer.cpp:1:
../../include/engine.hpp:54:2: note: declared here
  Module() DEPRECATED {}
  ^~~~~~
src/DrumsMixer.cpp: In constructor ‘DrumsMixerWidget::DrumsMixerWidget()’:
src/DrumsMixer.cpp:478:14: error: ‘createValueLight’ was not declared in this scope
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
              ^~~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: error: ‘GreenValueLight’ was not declared in this scope
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: error: template argument 1 is invalid
src/DrumsMixer.cpp:479:42: error: the value of ‘GreenValueLight’ is not usable in a constant expression
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(100+8, 280+5), &module->ch2MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: note: ‘GreenValueLight’ was not declared ‘constexpr’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:479:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(100+8, 280+5), &module->ch2MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:479:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:480:42: error: the value of ‘GreenValueLight’ is not usable in a constant expression
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(150+8, 280+5), &module->ch3MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: note: ‘GreenValueLight’ was not declared ‘constexpr’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:480:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(150+8, 280+5), &module->ch3MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:480:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:481:42: error: the value of ‘GreenValueLight’ is not usable in a constant expression
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(200+8, 280+5), &module->ch4MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: note: ‘GreenValueLight’ was not declared ‘constexpr’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:481:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(200+8, 280+5), &module->ch4MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:481:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:482:42: error: the value of ‘GreenValueLight’ is not usable in a constant expression
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(250+8, 280+5), &module->ch5MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: note: ‘GreenValueLight’ was not declared ‘constexpr’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:482:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(250+8, 280+5), &module->ch5MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:482:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:483:42: error: the value of ‘GreenValueLight’ is not usable in a constant expression
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(300+8, 280+5), &module->ch6MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: note: ‘GreenValueLight’ was not declared ‘constexpr’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:483:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(300+8, 280+5), &module->ch6MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:483:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:484:42: error: the value of ‘GreenValueLight’ is not usable in a constant expression
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(350+8, 280+5), &module->ch7MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: note: ‘GreenValueLight’ was not declared ‘constexpr’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:484:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(350+8, 280+5), &module->ch7MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:484:42: note:   expected a type, got ‘GreenValueLight’
src/DrumsMixer.cpp:485:42: error: the value of ‘GreenValueLight’ is not usable in a constant expression
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(400+8, 280+5), &module->ch8MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:478:42: note: ‘GreenValueLight’ was not declared ‘constexpr’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(50+8, 280+5), &module->ch1MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:485:42: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::SmallLight’
     addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(400+8, 280+5), &module->ch8MuteLight));
                                          ^~~~~~~~~~~~~~~
src/DrumsMixer.cpp:485:42: note:   expected a type, got ‘GreenValueLight’
../../compile.mk:53: recipe for target 'build/src/DrumsMixer.cpp.o' failed
make: *** [build/src/DrumsMixer.cpp.o] Error 1

**Comment by asbaklm** [comment]
The sourcecode on Github is old and it seems that it may not be getting refreshed. Instead, 0.5.0 versions need to be obtained from here:

https://www.autodafe.net/virtual-instruments/vcv-rack-modules/autodafe-module-pack-for-vcv-rack.html

**Comment by WnP** [comment]
Hi @antoniograzioli,

It would be nice if you can upload the latest released version of source code here, that way people can help you maintaining the code base.

Let me know your through
